#url????
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    username: root
    password: "zyc"
    url: jdbc:mysql://localhost:3306/common?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
